# Generated by Django 5.2.12 on 2026-04-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('subject_code', models.CharField(max_length=50)),
                ('subject_name', models.CharField(max_length=150)),
                ('exam_type', models.CharField(max_length=50)),
                ('total_marks', models.IntegerField(default=60)),
                ('paper_data', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
