# Generated by Django 4.2.7 on 2026-04-01 22:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PYQGenerationRequest',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('semester', models.IntegerField()),
                ('exam_type', models.CharField(choices=[('mid_term', 'Mid Term'), ('end_term', 'End Term'), ('practice', 'Practice')], default='practice', max_length=20)),
                ('num_questions', models.IntegerField(default=10)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('generated_pdf', models.FileField(blank=True, null=True, upload_to='pyqs/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('downloaded', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, related_name='pyq_requests', to='academics.course')),
            ],
            options={
                'verbose_name': 'PYQ Generation Request',
                'verbose_name_plural': 'PYQ Generation Requests',
                'db_table': 'pyq_generation_requests',
                'ordering': ['-generated_at'],
            },
        ),
    ]
