# Generated by Django 4.2.7 on 2026-04-01 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('pyqs', '0001_initial'),
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyqgenerationrequest',
            name='student',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='pyq_requests', to='users.student'),
        ),
        migrations.AddField(
            model_name='pyqgenerationrequest',
            name='subject',
            field=models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.CASCADE, related_name='pyq_requests', to='academics.subject'),
        ),
    ]
