# Generated by Django 4.2.7 on 2026-04-06 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0004_timetableslot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_type', models.CharField(choices=[('consecutive_absent', 'Consecutive Absences'), ('low_percentage', 'Low Attendance Percentage'), ('irregular_pattern', 'Irregular Pattern'), ('sudden_drop', 'Sudden Drop')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('description', models.TextField(blank=True, help_text='LLM-generated faculty alert')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_anomalies', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='academics.subject')),
            ],
            options={
                'db_table': 'ai_attendance_anomalies',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('parent_phone_number', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_face_registered', models.BooleanField(default=False)),
                ('is_details_filled', models.BooleanField(default=False)),
                ('face_registered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_student_profiles',
            },
        ),
        migrations.CreateModel(
            name='LectureSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('total_students', models.IntegerField(default=0, help_text='Faculty manually enters class strength')),
                ('session_type', models.CharField(choices=[('lecture', 'Lecture'), ('lab', 'Lab'), ('tutorial', 'Tutorial')], default='lecture', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('qr_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('qr_expires_at', models.DateTimeField(blank=True, null=True)),
                ('qr_image_path', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_lecture_sessions', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_sessions', to='academics.subject')),
            ],
            options={
                'db_table': 'ai_lecture_sessions',
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='FaceEncoding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding_path', models.CharField(help_text='Relative path to .pkl in MEDIA_ROOT', max_length=500)),
                ('encoding_count', models.IntegerField(default=0, help_text='Number of face samples (max 5)')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_encoding', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_face_encodings',
            },
        ),
        migrations.CreateModel(
            name='AttendanceNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('student_alert', 'Student Alert'), ('faculty_info', 'Faculty Info'), ('admin_critical', 'Admin Critical')], max_length=30)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_notifications', to=settings.AUTH_USER_MODEL)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='attendance_ai.attendanceanomaly')),
            ],
            options={
                'db_table': 'ai_attendance_notifications',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], default='absent', max_length=20)),
                ('marked_via', models.CharField(choices=[('qr_link', 'QR Link'), ('face_recognition', 'Face Recognition'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('confidence_score', models.FloatField(blank=True, help_text='Face recognition confidence 0-100', null=True)),
                ('snapshot_path', models.CharField(blank=True, max_length=500, null=True)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(blank=True, help_text='Student IP logged on QR mark', max_length=45)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance_ai.lecturesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_attendance_records',
                'ordering': ['-marked_at'],
                'unique_together': {('session', 'student')},
            },
        ),
    ]
