# Generated by Django 4.2.7 on 2026-04-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='registered_face_photo',
            field=models.ImageField(blank=True, null=True, upload_to='registered_faces/'),
        ),
    ]
