# Generated by Django 5.2.13 on 2026-04-22 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance_ai", "0002_studentprofile_registered_face_photo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancerecord",
            name="device_id",
            field=models.CharField(
                blank=True, help_text="Browser device fingerprint", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="device_verified",
            field=models.BooleanField(
                default=False, help_text="True if device matched binding"
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="gps_verified",
            field=models.BooleanField(
                default=False, help_text="True if GPS passed geofence check"
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="latitude",
            field=models.FloatField(
                blank=True, help_text="Student GPS lat at mark time", null=True
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="liveness_passed",
            field=models.BooleanField(
                default=False, help_text="True if liveness check passed"
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="liveness_score",
            field=models.FloatField(
                blank=True, help_text="Liveness score 0.0-1.0", null=True
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="longitude",
            field=models.FloatField(
                blank=True, help_text="Student GPS lng at mark time", null=True
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="security_score",
            field=models.FloatField(
                blank=True, help_text="Composite security score 0-100", null=True
            ),
        ),
        migrations.AddField(
            model_name="lecturesession",
            name="classroom_lat",
            field=models.FloatField(
                blank=True, help_text="Classroom GPS latitude", null=True
            ),
        ),
        migrations.AddField(
            model_name="lecturesession",
            name="classroom_lng",
            field=models.FloatField(
                blank=True, help_text="Classroom GPS longitude", null=True
            ),
        ),
        migrations.AddField(
            model_name="lecturesession",
            name="geofence_radius",
            field=models.IntegerField(default=50, help_text="Allowed radius in metres"),
        ),
        migrations.AddField(
            model_name="lecturesession",
            name="qr_refresh_secs",
            field=models.IntegerField(
                default=60, help_text="QR token rotation interval (seconds)"
            ),
        ),
        migrations.CreateModel(
            name="StudentDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        help_text="Browser UUID from localStorage", max_length=200
                    ),
                ),
                (
                    "device_ua",
                    models.CharField(
                        blank=True,
                        help_text="User-Agent at registration",
                        max_length=500,
                    ),
                ),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trusted_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_student_devices",
                "ordering": ["-registered_at"],
                "unique_together": {("student", "device_id")},
            },
        ),
    ]
