# Generated by Django 4.2.7 on 2026-04-06 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('total_actions', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'analytics_session',
                'ordering': ['-last_active'],
                'indexes': [models.Index(fields=['first_seen'], name='analytics_s_first_s_1519ce_idx'), models.Index(fields=['last_active'], name='analytics_s_last_ac_9218e7_idx')],
            },
        ),
        migrations.CreateModel(
            name='ResumeBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('skills', models.TextField(blank=True, default='[]')),
                ('exp_count', models.IntegerField(default=0)),
                ('edu_count', models.IntegerField(default=0)),
                ('project_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_builds', to='analytics.session')),
            ],
            options={
                'db_table': 'analytics_resumebuild',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session', 'created_at'], name='analytics_r_session_50430a_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('skills_tested', models.TextField(blank=True, default='[]')),
                ('total_questions', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('score_percent', models.FloatField(default=0.0)),
                ('grade', models.CharField(choices=[('Beginner', 'Beginner'), ('Learner', 'Learner'), ('Proficient', 'Proficient'), ('Expert', 'Expert')], default='Beginner', max_length=20)),
                ('ai_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='analytics.session')),
            ],
            options={
                'db_table': 'analytics_quizattempt',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session', 'created_at'], name='analytics_q_session_d894d0_idx')],
            },
        ),
        migrations.CreateModel(
            name='LearningRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('topics', models.TextField(blank=True, default='[]')),
                ('free_only', models.BooleanField(default=False)),
                ('resource_count', models.IntegerField(default=0)),
                ('ai_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_requests', to='analytics.session')),
            ],
            options={
                'db_table': 'analytics_learningrequest',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session', 'created_at'], name='analytics_l_session_3ccfd0_idx')],
            },
        ),
        migrations.CreateModel(
            name='InternshipSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('domain', models.CharField(blank=True, max_length=100)),
                ('min_stipend', models.IntegerField(default=0)),
                ('max_stipend', models.IntegerField(default=999999)),
                ('skills', models.TextField(blank=True, default='[]')),
                ('result_count', models.IntegerField(default=0)),
                ('ai_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internship_searches', to='analytics.session')),
            ],
            options={
                'db_table': 'analytics_internshipsearch',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session', 'created_at'], name='analytics_i_session_e88b50_idx')],
            },
        ),
        migrations.CreateModel(
            name='FitAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('match_score', models.FloatField(blank=True, null=True)),
                ('fit_prediction', models.CharField(blank=True, max_length=50, null=True)),
                ('fit_confidence', models.FloatField(blank=True, null=True)),
                ('matched_skills', models.TextField(blank=True, default='[]')),
                ('missing_skills', models.TextField(blank=True, default='[]')),
                ('resume_preview', models.TextField(blank=True)),
                ('job_preview', models.TextField(blank=True)),
                ('model_type', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fit_analyses', to='analytics.session')),
            ],
            options={
                'db_table': 'analytics_fitanalysis',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session', 'created_at'], name='analytics_f_session_743f22_idx')],
            },
        ),
        migrations.CreateModel(
            name='CareerSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('interests', models.TextField(blank=True, default='[]')),
                ('current_skills', models.TextField(blank=True)),
                ('experience', models.CharField(blank=True, max_length=50)),
                ('result_count', models.IntegerField(default=0)),
                ('ai_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_searches', to='analytics.session')),
            ],
            options={
                'db_table': 'analytics_careersearch',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session', 'created_at'], name='analytics_c_session_5e18a0_idx')],
            },
        ),
    ]
