# Generated by Django 4.2.7 on 2026-04-01 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semesterresult',
            name='student',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='semester_results', to='users.student'),
        ),
        migrations.AlterUniqueTogether(
            name='semesterresult',
            unique_together={('student', 'semester')},
        ),
    ]
