# Generated by Django 4.2.7 on 2026-04-01 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='credits',
            field=models.IntegerField(default=0, help_text='Total Graduation Credits'),
        ),
        migrations.AddField(
            model_name='course',
            name='desc',
            field=models.TextField(blank=True, help_text='Program Summary Description', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(blank=True, help_text='Undergraduate, Postgraduate, etc.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
    ]
