# Generated by Django 4.2.7 on 2026-04-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0004_timetableslot"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="campus_branch",
            field=models.CharField(
                choices=[
                    ("Kherva", "Kherva (Mehsana)"),
                    ("Ahmedabad", "Ahmedabad"),
                    ("Both", "Both Campuses"),
                ],
                default="Kherva",
                help_text="Campus where this subject is offered",
                max_length=20,
            ),
        ),
    ]
