# Generated by Django 4.2.7 on 2026-04-09 21:49
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0006_add_exam_and_result_models"),
    ]

    operations = [
        # Create Room model
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "room_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("room_number", models.CharField(max_length=20, unique=True)),
                ("building", models.CharField(max_length=50)),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("Lecture Hall", "Lecture Hall"),
                            ("Lab", "Computer Lab"),
                            ("Workshop", "Workshop"),
                            ("Seminar Hall", "Seminar Hall"),
                            ("Tutorial Room", "Tutorial Room"),
                        ],
                        default="Lecture Hall",
                        max_length=20,
                    ),
                ),
                ("capacity", models.IntegerField(default=60)),
                ("floor", models.IntegerField(default=1)),
                (
                    "campus_branch",
                    models.CharField(
                        choices=[
                            ("Kherva", "Kherva (Mehsana)"),
                            ("Ahmedabad", "Ahmedabad"),
                        ],
                        default="Kherva",
                        max_length=20,
                    ),
                ),
                ("has_projector", models.BooleanField(default=False)),
                ("has_computers", models.BooleanField(default=False)),
                ("is_available", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Room",
                "verbose_name_plural": "Rooms",
                "db_table": "rooms",
                "ordering": ["building", "room_number"],
            },
        ),
        # Create TimeSlot model
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "slot_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "slot_order",
                    models.IntegerField(
                        default=0, help_text="Order in day (1, 2, 3...)"
                    ),
                ),
                ("duration_minutes", models.IntegerField(default=60)),
                ("is_break", models.BooleanField(default=False)),
                (
                    "campus_branch",
                    models.CharField(
                        choices=[("Kherva", "Kherva"), ("Ahmedabad", "Ahmedabad")],
                        default="Kherva",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Time Slot",
                "verbose_name_plural": "Time Slots",
                "db_table": "time_slots",
                "ordering": ["slot_order"],
            },
        ),
        # Create TimetableTemplate model
        migrations.CreateModel(
            name="TimetableTemplate",
            fields=[
                (
                    "template_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("semester", models.IntegerField()),
                (
                    "campus_branch",
                    models.CharField(
                        choices=[("Kherva", "Kherva"), ("Ahmedabad", "Ahmedabad")],
                        default="Kherva",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_templates",
                        to="academics.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Timetable Template",
                "verbose_name_plural": "Timetable Templates",
                "db_table": "timetable_templates",
            },
        ),
        # Create TimetableSchedule model
        migrations.CreateModel(
            name="TimetableSchedule",
            fields=[
                (
                    "schedule_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_active", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=False)),
                ("generated_by", models.CharField(default="manual", max_length=20)),
                ("generation_log", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_term",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timetable_schedules",
                        to="academics.academicterm",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schedules",
                        to="academics.timetabletemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Timetable Schedule",
                "verbose_name_plural": "Timetable Schedules",
                "db_table": "timetable_schedules",
                "ordering": ["-start_date"],
            },
        ),
        # Create FacultyAvailability model
        migrations.CreateModel(
            name="FacultyAvailability",
            fields=[
                (
                    "availability_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                            ("Saturday", "Saturday"),
                        ],
                        max_length=10,
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("preferred_slots", models.JSONField(blank=True, default=list)),
                ("not_available_slots", models.JSONField(blank=True, default=list)),
                (
                    "campus_branch",
                    models.CharField(
                        choices=[("Kherva", "Kherva"), ("Ahmedabad", "Ahmedabad")],
                        default="Kherva",
                        max_length=20,
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability",
                        to="users.faculty",
                    ),
                ),
            ],
            options={
                "verbose_name": "Faculty Availability",
                "verbose_name_plural": "Faculty Availabilities",
                "db_table": "faculty_availability",
            },
        ),
        # Create TimetableConflict model
        migrations.CreateModel(
            name="TimetableConflict",
            fields=[
                (
                    "conflict_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "conflict_type",
                    models.CharField(
                        choices=[
                            ("Room", "Room Conflict"),
                            ("Faculty", "Faculty Conflict"),
                            ("Student", "Student Group Conflict"),
                            ("Time", "Time Slot Conflict"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolution", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_conflicts",
                        to="users.user",
                    ),
                ),
                (
                    "slot_1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflicts_as_first",
                        to="academics.timetableslot",
                    ),
                ),
                (
                    "slot_2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflicts_as_second",
                        to="academics.timetableslot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Timetable Conflict",
                "verbose_name_plural": "Timetable Conflicts",
                "db_table": "timetable_conflicts",
            },
        ),
        # Add new fields to existing TimetableSlot
        migrations.AddField(
            model_name="timetableslot",
            name="generated_by",
            field=models.CharField(default="manual", max_length=20),
        ),
        migrations.AddField(
            model_name="timetableslot",
            name="is_auto_generated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="timetableslot",
            name="is_locked",
            field=models.BooleanField(
                default=False, help_text="Prevent auto-regeneration"
            ),
        ),
        migrations.AddField(
            model_name="timetableslot",
            name="priority",
            field=models.IntegerField(default=5, help_text="1=highest, 10=lowest"),
        ),
        migrations.AddField(
            model_name="timetableslot",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="timetable_slots",
                to="academics.room",
            ),
        ),
        migrations.AddField(
            model_name="timetableslot",
            name="room_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="timetableslot",
            name="slot_type",
            field=models.CharField(
                choices=[
                    ("Theory", "Theory"),
                    ("Practical", "Practical"),
                    ("Tutorial", "Tutorial"),
                    ("Lab", "Lab"),
                ],
                default="Theory",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="timetableslot",
            name="time_slot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="timetable_slots",
                to="academics.timeslot",
            ),
        ),
        migrations.AddField(
            model_name="timetableslot",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="timetableslot",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        # Add unique constraint to FacultyAvailability
        migrations.AddConstraint(
            model_name="facultyavailability",
            constraint=models.UniqueConstraint(
                fields=("faculty", "day_of_week"), name="unique_faculty_day"
            ),
        ),
    ]
