# Generated by Django 4.2.7 on 2026-04-10 07:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_add_shifts_and_daytypes"),
        ("academics", "0007_add_smart_timetable_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="BreakSlot",
            fields=[
                (
                    "break_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "break_type",
                    models.CharField(
                        choices=[
                            ("Tea", "Tea Break"),
                            ("Lunch", "Lunch Break"),
                            ("Prayer", "Prayer Break"),
                            ("Other", "Other"),
                        ],
                        default="Lunch",
                        max_length=20,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("duration_minutes", models.IntegerField(default=30)),
                (
                    "campus_branch",
                    models.CharField(
                        choices=[
                            ("Kherva", "Kherva"),
                            ("Ahmedabad", "Ahmedabad"),
                            ("Both", "Both Campuses"),
                        ],
                        default="Kherva",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Break Slot",
                "verbose_name_plural": "Break Slots",
                "db_table": "break_slots",
                "ordering": ["start_time"],
            },
        ),
        migrations.CreateModel(
            name="DayType",
            fields=[
                (
                    "day_type_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "day_type",
                    models.CharField(
                        choices=[
                            ("weekday", "Weekday (Mon-Fri)"),
                            ("saturday", "Saturday"),
                            ("sunday", "Sunday"),
                            ("holiday", "Holiday"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("has_full_day", models.BooleanField(default=True)),
                (
                    "campus_branch",
                    models.CharField(
                        choices=[
                            ("Kherva", "Kherva"),
                            ("Ahmedabad", "Ahmedabad"),
                            ("Both", "Both Campuses"),
                        ],
                        default="Kherva",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Day Type",
                "verbose_name_plural": "Day Types",
                "db_table": "day_types",
            },
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "shift_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("start_time", models.TimeField(help_text="Shift start time")),
                ("end_time", models.TimeField(help_text="Shift end time")),
                (
                    "campus_branch",
                    models.CharField(
                        choices=[
                            ("Kherva", "Kherva"),
                            ("Ahmedabad", "Ahmedabad"),
                            ("Both", "Both Campuses"),
                        ],
                        default="Kherva",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Shift",
                "verbose_name_plural": "Shifts",
                "db_table": "shifts",
                "ordering": ["display_order"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="facultyavailability",
            name="unique_faculty_day",
        ),
        migrations.AddField(
            model_name="timeslot",
            name="break_type",
            field=models.CharField(
                choices=[
                    ("None", "Lecture Slot"),
                    ("Tea", "Tea Break"),
                    ("Lunch", "Lunch Break"),
                    ("Prayer", "Prayer Break"),
                ],
                default="None",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="facultyavailability",
            name="not_available_slots",
            field=models.JSONField(
                blank=True, default=list, help_text="List of unavailable time slot IDs"
            ),
        ),
        migrations.AlterField(
            model_name="facultyavailability",
            name="preferred_slots",
            field=models.JSONField(
                blank=True, default=list, help_text="List of preferred time slot IDs"
            ),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="campus_branch",
            field=models.CharField(
                choices=[
                    ("Kherva", "Kherva"),
                    ("Ahmedabad", "Ahmedabad"),
                    ("Both", "Both Campuses"),
                ],
                default="Kherva",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="timetableconflict",
            name="slot_1",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conflicts_as_first",
                to="academics.timetableslot",
            ),
        ),
        migrations.AlterField(
            model_name="timetableconflict",
            name="slot_2",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conflicts_as_second",
                to="academics.timetableslot",
            ),
        ),
        migrations.AlterField(
            model_name="timetableschedule",
            name="academic_term",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="timetable_schedules",
                to="academics.academicterm",
            ),
        ),
        migrations.AlterField(
            model_name="timetableschedule",
            name="template",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schedules",
                to="academics.timetabletemplate",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="facultyavailability",
            unique_together={("faculty", "day_of_week")},
        ),
        migrations.AddField(
            model_name="timeslot",
            name="day_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Day type this slot applies to (null = all days)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="slots",
                to="academics.daytype",
            ),
        ),
        migrations.AddField(
            model_name="timeslot",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated shift (optional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="slots",
                to="academics.shift",
            ),
        ),
    ]
