# Generated by Django 4.2.7 on 2026-04-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0008_add_shifts_and_daytypes"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="shift",
            field=models.CharField(
                choices=[
                    ("MORNING", "Morning (8:00 AM - 1:00 PM)"),
                    ("NOON", "Noon (12:00 PM - 6:10 PM)"),
                ],
                default="NOON",
                help_text="Timetable shift for this course",
                max_length=10,
            ),
        ),
    ]
