# Generated by Django 4.2.7 on 2026-04-14 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("academics", "0009_add_shift_to_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimetablePublishStatus",
            fields=[
                (
                    "publish_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("semester", models.IntegerField()),
                ("section", models.CharField(default="A", max_length=10)),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publish_statuses",
                        to="academics.course",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Timetable Publish Status",
                "verbose_name_plural": "Timetable Publish Statuses",
                "db_table": "timetable_publish_status",
                "unique_together": {("course", "semester", "section")},
            },
        ),
    ]
