# Generated by Django 4.2.7 on 2026-04-14 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("academics", "0010_timetablepublishstatus"),
    ]

    operations = [
        migrations.CreateModel(
            name="SemesterConfig",
            fields=[
                (
                    "config_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "current_parity",
                    models.CharField(
                        choices=[("ODD", "Odd Semester"), ("EVEN", "Even Semester")],
                        default="ODD",
                        max_length=4,
                    ),
                ),
                ("is_odd_enabled", models.BooleanField(default=True)),
                ("is_even_enabled", models.BooleanField(default=False)),
                ("last_toggled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "timetable_generated",
                    models.BooleanField(
                        default=False,
                        help_text="Set to True after AI timetable generation. Resets on semester toggle.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "toggled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="semester_toggles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Semester Config",
                "verbose_name_plural": "Semester Configs",
                "db_table": "semester_config",
            },
        ),
        migrations.DeleteModel(
            name="TimetablePublishStatus",
        ),
    ]
