# Generated by Django 4.2.7 on 2026-04-01 22:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], default='present', max_length=10)),
                ('method', models.CharField(choices=[('manual', 'Manual'), ('ml_face_recognition', 'ML Face Recognition')], default='manual', max_length=25)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, help_text='Confidence score for ML-based attendance (0-100)', max_digits=5, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance Records',
                'db_table': 'attendance',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section', models.CharField(default='Section A', max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('room', models.CharField(max_length=20)),
                ('duration', models.IntegerField(default=90, help_text='Duration in minutes')),
                ('attendance_marked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Class Session',
                'verbose_name_plural': 'Class Sessions',
                'db_table': 'class_sessions',
                'ordering': ['date', 'time'],
            },
        ),
    ]
