# Generated by Django 4.2.7 on 2026-04-01 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('attendance', '0001_initial'),
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='faculty',
            field=models.ForeignKey(db_column='faculty_id', on_delete=django.db.models.deletion.CASCADE, related_name='class_sessions', to='users.faculty'),
        ),
        migrations.AddField(
            model_name='classsession',
            name='subject',
            field=models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.CASCADE, related_name='class_sessions', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='marked_by',
            field=models.ForeignKey(db_column='marked_by_faculty_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendance', to='users.faculty'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='users.student'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='subject',
            field=models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='academics.subject'),
        ),
    ]
