# Generated by Django 4.2.7 on 2026-04-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_face_registered',
            field=models.BooleanField(default=False, help_text='True when student has completed face onboarding'),
        ),
    ]
