# Generated by Django 4.2.7 on 2026-04-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_student_address_student_admission_year_student_batch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="faculty",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="faculty",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="faculty",
            name="designation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HOD", "Head of Department"),
                    ("Professor", "Professor"),
                    ("Associate Professor", "Associate Professor"),
                    ("Assistant Professor", "Assistant Professor"),
                    ("Lecturer", "Lecturer"),
                    ("Visiting Faculty", "Visiting Faculty"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="faculty",
            name="experience_years",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="faculty",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="faculty",
            name="qualification",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
