# Generated by Django 4.2.7 on 2026-04-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_faculty_address_faculty_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="faculty",
            name="branch",
            field=models.CharField(
                blank=True,
                help_text="Campus branch (Kherva Mehsana / Ahmedabad)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="branch",
            field=models.CharField(
                blank=True,
                help_text="Campus branch (Kherva Mehsana / Ahmedabad)",
                max_length=100,
                null=True,
            ),
        ),
    ]
