# Generated by Django 4.2.7 on 2026-04-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_faculty_class_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="faculty",
            name="max_lectures_per_day",
            field=models.IntegerField(
                default=6, help_text="Maximum lectures faculty can take per day"
            ),
        ),
        migrations.AddField(
            model_name="faculty",
            name="working_days",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of working days ['Monday', 'Tuesday', ...]",
            ),
        ),
        migrations.AddField(
            model_name="faculty",
            name="working_shift",
            field=models.CharField(
                choices=[
                    ("Morning", "Morning"),
                    ("Noon", "Noon"),
                    ("Evening", "Evening"),
                    ("Full Day", "Full Day"),
                ],
                default="Noon",
                help_text="Faculty working shift",
                max_length=20,
            ),
        ),
    ]
