# Generated by Django 4.2.7 on 2026-04-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_add_shifts_and_daytypes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faculty",
            name="working_shift",
            field=models.CharField(
                choices=[("Morning", "Morning"), ("Noon", "Noon")],
                default="Noon",
                help_text="Faculty working shift (Morning/Afternoon only - 1 faculty = 1 shift)",
                max_length=20,
            ),
        ),
    ]
