# Generated by Django 4.2.7 on 2026-04-12 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_remove_invalid_shifts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("faculty", "Faculty"),
                    ("admin", "Admin"),
                    ("super_admin", "Super Admin"),
                ],
                default="student",
                max_length=15,
            ),
        ),
        migrations.CreateModel(
            name="AdminActivityLog",
            fields=[
                (
                    "log_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("admin_name", models.CharField(blank=True, max_length=100)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Created"),
                            ("UPDATE", "Updated"),
                            ("DELETE", "Deleted"),
                            ("RESET_PASSWORD", "Reset Password"),
                            ("BAN", "Banned User"),
                            ("UNBAN", "Unbanned User"),
                            ("LOGIN", "Logged In"),
                            ("LOGOUT", "Logged Out"),
                            ("GENERATE", "Generated"),
                            ("CLEAR", "Cleared"),
                            ("IMPORT", "Imported"),
                            ("EXPORT", "Exported"),
                            ("OVERRIDE", "Overridden"),
                            ("SEND_NOTIFICATION", "Sent Notification"),
                            ("SYSTEM", "System Action"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "target_model",
                    models.CharField(
                        choices=[
                            ("User", "User"),
                            ("Student", "Student"),
                            ("Faculty", "Faculty"),
                            ("Admin", "Admin"),
                            ("Course", "Course"),
                            ("Subject", "Subject"),
                            ("TimetableSlot", "Timetable Slot"),
                            ("Attendance", "Attendance"),
                            ("Exam", "Exam"),
                            ("Result", "Result"),
                            ("Notification", "Notification"),
                            ("System", "System"),
                        ],
                        max_length=50,
                    ),
                ),
                ("target_id", models.CharField(blank=True, max_length=100, null=True)),
                ("target_name", models.CharField(blank=True, max_length=255)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "admin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin Activity Log",
                "verbose_name_plural": "Admin Activity Logs",
                "db_table": "admin_activity_logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["admin", "-timestamp"],
                        name="admin_activ_admin_i_336b22_idx",
                    ),
                    models.Index(
                        fields=["action", "-timestamp"],
                        name="admin_activ_action_21303d_idx",
                    ),
                    models.Index(
                        fields=["target_model", "-timestamp"],
                        name="admin_activ_target__381daf_idx",
                    ),
                ],
            },
        ),
    ]
