# Generated by Django 4.2.7 on 2026-04-13 22:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_add_super_admin_and_activity_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="faculty",
            name="is_hod",
            field=models.BooleanField(
                default=False, help_text="Whether this faculty is Head of Department"
            ),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="working_shift",
            field=models.CharField(
                choices=[
                    ("Morning", "Morning"),
                    ("Noon", "Noon"),
                    ("Evening", "Evening"),
                    ("Full Day", "Full Day"),
                ],
                default="Noon",
                help_text="Faculty working shift",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("faculty", "Faculty"),
                    ("admin", "Admin"),
                ],
                default="student",
                max_length=10,
            ),
        ),
        migrations.DeleteModel(
            name="AdminActivityLog",
        ),
    ]
