# Generated by Django 4.2.7 on 2026-04-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_faculty_is_hod_alter_faculty_working_shift_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="faculty",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_class_teacher", True)),
                fields=("class_course", "class_semester"),
                name="unique_class_teacher_per_course_sem",
            ),
        ),
    ]
