# Generated by Django 5.2.12 on 2026-04-26 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_passwordresetotp_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("view", "View"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                        ],
                        max_length=50,
                    ),
                ),
                ("target_model", models.CharField(max_length=100)),
                ("target_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "target_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="users.admin",
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin Activity Log",
                "verbose_name_plural": "Admin Activity Logs",
                "db_table": "admin_activity_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["admin", "-created_at"],
                        name="admin_activ_admin_i_317756_idx",
                    ),
                    models.Index(
                        fields=["action", "-created_at"],
                        name="admin_activ_action_63b716_idx",
                    ),
                ],
            },
        ),
    ]
